# Generated by Django 3.0.5 on 2020-11-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_announcement_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
    ]
