# Generated by Django 3.0.5 on 2020-11-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='nome',
            new_name='name',
        ),
    ]
